# Generated by Django 3.2.5 on 2021-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_product1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_product2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
