# Generated by Django 2.2 on 2021-07-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_shippingaddress_kode_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo_category',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
