# Generated by Django 2.2 on 2021-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210328_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='kode_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='kota',
            field=models.CharField(default='bogor', max_length=255),
        ),
    ]
