# Generated by Django 2.2 on 2021-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_logo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_product',
            new_name='image_product_1',
        ),
        migrations.AddField(
            model_name='product',
            name='image_product_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
