# Generated by Django 5.2.3 on 2025-06-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
